services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
